name: Build with OpenFOAM v2406
on:
  push:
    branches-ignore:
      - 'OpenFOAM*'
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
  pull_request:
    branches-ignore:
      - 'OpenFOAM*'
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
jobs:
  build-fe40:
    runs-on: ubuntu-20.04
    container: ghcr.io/hoehnp/openfoam-adapter:precice-foam-extend-4.0
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: foam-extend-4.0
    - name: Build OpenFOAM-preCICE adapter
      run: ./Allwmake
  build-fe41:
    runs-on: ubuntu-22.04
    container: ghcr.io/hoehnp/openfoam-adapter:precice-foam-extend-4.1
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: foam-extend-4.1
    - name: Build OpenFOAM-preCICE adapter
      run: ./Allwmake
  build-fe50:
    runs-on: ubuntu-22.04
    container: ghcr.io/hoehnp/openfoam-adapter:precice-foam-extend-5.0
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: foam-extend-5.0
    - name: Build OpenFOAM-preCICE adapter
      run: ./Allwmake
  build-fedev:
    runs-on: ubuntu-22.04
    container: ghcr.io/hoehnp/openfoam-adapter:precice-foam-extend-dev
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: foam-extend-5.1
    - name: Build OpenFOAM-preCICE adapter
      run: ./Allwmake
