name: Build with foam-extend-4.1
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
  pull_request:
    branches-ignore:
      - 'OpenFOAM*'
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
jobs:
  build-fe41:
    runs-on: ubuntu-latest
    container: mgoltzsche/podman:5.5.2-minimal
    steps:
    - name: Install git
      run: apk add git
    - name: Check out repository
      run: cd /tmp; git clone https://github.com/precice/foam-extend-adapter foam-extend-adapter
    - name: Check out branch
      run: cd /tmp/foam-extend-adapter; git checkout foam-extend-4.1
    - name: Build OpenFOAM-preCICE adapter
      run: cd /tmp/foam-extend-adapter/docker; ls; ./test-fe41.sh
