name: Build with foam-extend-4.1
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
  pull_request:
    branches-ignore:
      - 'OpenFOAM*'
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
jobs:
  build-fe41:
    runs-on: ubuntu-22.04
    container: ghcr.io/hoehnp/openfoam-adapter:precice-foam-extend-4.1
    steps:
    - name: Who am I
      run: whoami
    - name: Check out repository
      run: git clone https://github.com/precice/foam-extend-adapter foam-extend-adapter
    - name: Check out branch
      run: cd foam-extend-adapter; git checkout foam-extend-4.1
    - name: Build OpenFOAM-preCICE adapter
      run: ./Allwmake
